# Workflow name
name: Build
on:
# When it will be triggered
# And in which branch
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
# Where will they run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    ## Checkout our repository ###
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up our JDK environment
      uses: actions/setup-java@v3
      with:
          distribution: 'corretto'
          java-version: '17'
          cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run detekt
      run: ./gradlew detekt

    - name: Run android lint
      run: ./gradlew lintDebug

    - name: Run unit tests
      run: ./gradlew testDebugUnitTest

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.3
      with :
          name: DemoApp.apk
          path: app/build/outputs/apk/debug/app-debug.apk
    #- uses: actions/download-artifact@v3
    #  with:
    #    name: debugApk
    #    path: app/build/outputs/apk/debug/app-debug.apk